FROM golang:1.25-alpine

RUN apk add --no-cache git curl bash nodejs npm

RUN go install github.com/air-verse/air@latest \
 && go install github.com/swaggo/swag/cmd/swag@latest

WORKDIR /app

COPY go.mod go.sum* ./
RUN go mod download || true

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
